version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"  # Adjust this version if needed

python:
  install:
    - method: setuptools
      path: .
    - requirements: docs/requirements.txt  # Optional: if you have doc-specific deps

sphinx:
  configuration: docs/source/conf.py

